"""Automatically generated by Nx."""
from hotel_management.hotel_search_wrapper import HotelSearchWrapper, hotel_search_service
from hotel_management.saved_hotels import SavedHotelsService, saved_hotels_service
from hotel_management.hotel_management_service import HotelManagementService, hotel_management_service

__all__ = [
    "HotelSearchWrapper",
    "hotel_search_service",
    "SavedHotelsService",
    "saved_hotels_service",
    "HotelManagementService",
    "hotel_management_service",
]
